version: 1
genesis:
  chain-id: resyr-localnet
  app_state:
    staking:
      params:
        bond_denom: "uresyr"
accounts:
- name: alice
  coins:
  - 200000000uresyr
- name: bob
  coins:
  - 100000000uresyr
- name: carol
  coins:
  - 100000000uresyr
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 100000uresyr
validators:
- name: alice
  bonded: 100000000uresyr